# Generated by Django 3.0.2 on 2020-01-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DruzynGaming', '0002_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nick',
            field=models.CharField(default='nick', help_text='Nick', max_length=30),
            preserve_default=False,
        ),
    ]
