# Generated by Django 3.0.2 on 2020-01-31 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DruzynGaming', '0003_player_nick'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tytuł', max_length=30)),
                ('details', models.TextField(help_text='Szczegóły')),
            ],
        ),
        migrations.CreateModel(
            name='Kalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DruzynGaming.Event')),
            ],
        ),
    ]
